# Jupyter: What is this file?

**Before we start a Primer/Reminder of Python, we'll introduce Jupyter Notebooks:**

- This file is a Jupyter notebook. 
- In this class we will use these files when solving interactive problems in Python. 
- The Jupyter application is incuded in the Anaconda installation that you must have installed on your laptop by now. 

- Jupyter notebooks allow you to read text, click on links, and modify and run code interactively all at the same time. 
- If you are interested in modifying Jupyter notebooks, and even creating your own in the future, there are tons of resources (turorials and videos) online to help. 
- You can also use these provided files as a way of teaching yourself how to edit and eventually create your own.

**Below is some basic info:**

The most commonly used types of entries you will make inculde:
- Markdown: (this box) Includes text and notes, look up available resources for formatting (e.g., how to go to new line, how to insert equation, how to write in bold, insert bullet points etc)
- Code: Python code 
- Double-click on each "box" to see the code/editable text.
- Click on "Run" to transform the code into "final product". This should make the Markdown look like a document and run code and display results underneath. 

**You must learn how to use Jupyter notebooks because our exams will be in the form of Jupyter notebooks. It will also be very convenient for you and us to work on homework assignments and the class project in Jupyter.**


# What is Python and its main differences to Matlab?
*These notes are built upon material from:* https://github.com/jrjohansson/scientific-python-lectures*

Python is a modern, free, general-purpose high-level programming language. Python is used a lot for data analysis and its usage is growing rapidly.

Two resources contain some discussion on the differences between Matlab and Python: 
1. [Python versus Matlab](http://www.pyzo.org/python_vs_matlab.html)
2. [Overview of differences between Matlab and Python](https://bastibe.de/2013-01-20-a-python-primer-for-matlab-users.html)

**Users and developers are finding Python to have certain advantages, such as:**
-  Flexibility, it's free and open source, large community that shares material

**Of course Matlab still has some advantages over Python:**
-  Specialized toolboxes (i.e., simulink), handling of matrices, speed, handling of new versions is less of an issue, user-friendly interface.

**Python "Packages":**
These extend the functionality in Python. Similar to "toolboxes" in Matlab. In this class, we will use some of the following:
-  numpy (matrix operations)
-  scipy (scientific algorithms)
-  matplotlib (plotting)
-  pyomo (optimization)
-  scikit-learn (machine learning)

**Anaconda (Conda):**
Managing packages and versions is one of the main challenges with python. (i.e., if a package is built upon a different version, it might not work in a new version). Platforms like Anaconda are cross-platform installation packages of Python, that aim to make this a bit easier for you. Please follow the instructions on the provided instructions file to download everything you need to use in this class.

**Graphical User Interface (Spyder):**
With the Anaconda installation, you have access to an interface of Python, that is more user-friendly than writing scripts and running code on the console or terminal. If you open Spyder, you will notice it has a default setup:
-  **On the left**, a temporary file is created (**temp.py**). This is where you will start writing a function, that you can store as a .py file to run/execute later.
-  On the **bottom right**, you have the **Console**. Here you can interactively execute commands, like the ones we will go over today.


### Now let's run our first Python commands and create our first Python files:

*Step 1: Open Spyder and type the following examples in your console for now to reproduce the results in this file:*


In [1]:
a = 10 #no semicolon is needed at end of line!
print(a)
print(type(a))
b = 1.
print(b)
print(type(b))
c=a+b
print(c)

10
<class 'int'>
1.0
<class 'float'>
11.0


In [2]:
z = 'hello'
print(z)
print(type(z))
w = c + z
print(w)

hello
<class 'str'>


TypeError: unsupported operand type(s) for +: 'float' and 'str'

**Observations:**
- When you set a equal to 10, it automatically assumes it is an integer number. 
- When you specify it as 1. it sets it to a real number (with significant digits). That is called a floating point number.
- When you added an integer and a real number, you got a real number.
- When you tried to add two incompatible types (float + string), you got an **error**.
- Be careful with variable types, because they do not change, unless you specify it with your code.

**Lists:** Defined with brackets and comma to separate numbers or text:

In [3]:
a = [1,2,3]
print(a)
print(type(a))
b = ['d','a','t','a']
print(b)
print(type(b))

[1, 2, 3]
<class 'list'>
['d', 'a', 't', 'a']
<class 'list'>


As we mentioned above, we need to use some **Packages** in most of the things that we want to do in python. That is why most functions start with importing the right packages. Each package, has functions that can be used as default functions, when the package is imported. 

-  You can import each package separately and give it a reference name:

In [4]:
import numpy as np
import scipy as sp
import matplotlib as mpl

#solve Ax = b
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,2,3])
x = np.linalg.solve(A,b)
print(x)

[-0.23333333  0.46666667  0.1       ]


-  You can import all above packages simultaneously. If you use following command *, you do not need to specify name. All functions become default functions:

In [5]:
from pylab import *
A = array([[1,2,3],[4,5,6],[7,8,9]])
b = array([1,2,3])
x = linalg.solve(A,b)
print(x)

[-0.23333333  0.46666667  0.1       ]


## Index in Arrays/Matrices:
-  Index starts from 0, NOT from 1.
-  Let's see some examples:

In [7]:
from pylab import *
m = linspace(10,100,10) #create array starting with 10, ending in 100 with 10 elements total:
print(m)
ten = m[0]
twenty = m[1]
m1 = m[6:8] #will show you elements 6 and 7 of array! NOT 6, 7 and 8
print(m1)


[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[70. 80.]


## Copying Variables does not work like in Matlab:

In [13]:
a = array([1,2,3,4,5])
b = a[1:4]
print(a)
print(b)
b[1] = rand() #will insert random number to both first element of a and of b
print(a)
print(b)

[1 2 3 4 5]
[2 3 4]
[1 2 0 4 5]
[2 0 4]


**To copy a variable do the following:**

In [9]:
a = array([1,2,3,4,5])
c = array(a[1:4],copy=True)
c[1] = rand() #this will only change c
print(a)
print(c)

#Also works if you omit "copy=True":
d=array(a[1:4])
d[1] = rand()
print(a)
print(d)

[1 2 3 4 5]
[2 0 4]
[1 2 3 4 5]
[2 0 4]


## **For** Loops: 
-  Everything you can do in Matlab, you can do here, with different syntax
-  No end statements needed

In [17]:
sum = 0
for n in [1,2,3,4,5]:
    sum = sum + n   
print(sum)
    

15


The **indentation level** is what informs Python of when a loop is done:

In [10]:
l = [1,2,3,4]
for item in l:
    print(item)

1
2
3
4


## IF STATEMENTS:

In [15]:
temp = 38.
if temp > 40:
    print('Wear shorts')
else:
    print('Wear pants')


Wear pants


In [16]:
score = 95
if score >=90:
    letter = 'A'
elif score >= 80:
    letter = 'B'
elif score >=70:
    letter = 'C'
else:
    letter = 'D'
print(letter)

A


## Defining functions:
**In Matlab, you would write:**

function [out] = abs(inp)

    if inp > 0
        out = inp
    else 
        out = -inp
    end 
end

**In Python you will write:**

In [17]:
def abs(inp):
    if inp>0:
        return inp
    else:
        return -inp


In [36]:
abs(-10)

10

## Creating and storing functions:
**Here we will create more complicated functions and store them as python files.**

### Single-Variable Optimization Example:
**Through this example, we will learn about:** <br>
 - Formulating a function <br>
 - Storing and calling .py files <br>
 - Loops <br>
 - <font color=red> **NOTE that what we will do below is NOT a way to solve an optimization problem!!!** </font>
<br>

#### Exercise 1.1:
**Find the minimum of function $f(x)= x^3-12x+3$ in the interval $-4<=x<=4$, where $x$ is an real valued variable. <br>
Complete the code below to do that:**


In [11]:
from pylab import *
fxmin = 100
l = linspace(-4,4,100)

for i in l:
    help = i**3 - 12*i + 3 # power in Python is "**" and not "^"
    if help < fxmin:
        fxmin = help      
print(fxmin)


-13.0


In [17]:
# What if x is an integer?
# We can solve it in two ways:

l1 = np.arange(-4, 4, dtype=int) # note that arange excludes right endpoint in the interval
l2 = np.linspace(-4, 4, 9, dtype=int) # '9' here is the number of samples we need
fxmin = 100

for i in l1:
    help = i**3 - 12*i + 3 # power in Python is "**" and not "^"
    if help < fxmin:
        fxmin = help      
print(fxmin)

for i in l2:
    help = i**3 - 12*i + 3 # power in Python is "**" and not "^"
    if help < fxmin:
        fxmin = help      
print(fxmin)


-13
-13


### Exercise 1.2: 
**Now, let's bring in the def functions. Re-write the above script but this time, let's store $f(x)$ as a def function.**


In [28]:
from pylab import *

def fx(x):
    out = x**3 - 12*x + 3
    return out

fxmin = 100
l = linspace(-4,4,100) 

for i in l:
    help = fx(i) 
    if help < fxmin:
        fxmin = help
print(fxmin)


-13.0


### Exercise 1.3: 
**Now open Spyder and copy-paste the above code into the Editor. <br> 
Save it as .py file into a directory and name that you prefer. <br>
Run the python script and observe the results in the console.** <br>

**Also to do:** <br>
 - After you have run the script, call function fx in the console for any random value. (i.e., fx(100), should give...?)
 - Can you call function fx for an array of values???? Try it, which one of below works and why??? <br>
 
*fx(100) = ???* <br>
*fx([1,2,3]) = ??? #ERROR* <br>
*fx(array([1,2,3])) = ???*

### Exercise 1.4 - part a:
**Modify your code to find the optimal solution to a problem that solves the following optimization problem (using loop and if statments):**<br>
$min$ $f(x)=x^3-12x+3$ <br>
subject to: <br>
$g(x)= x^2 - 3 <=0$ <br>
$x = real $ <br>
$-4<=x<=4$ <br>

### Exercise 1.4 - part b (more advanced):
**Find the same result, by using only arrays of functions $f(x)$ and $g(x)$ and numpy matrix operations!**

In [32]:
def fx(x):
    obj = x**3 -12*x + 3
    return obj

def gx(x):
    c = x**2-3
    return c

fxmin = 100
l = linspace(-4,4,100)
for i in l:
    help = fx(i)
    if gx(i) <= 0:
        if help < fxmin:
            fxmin =help
            print('best changed to:',fxmin)
print('final best:',fxmin)

#OR:
fxmin = 100
for i in l:
    help = fx(i)
    if gx(i) <= 0 and help < fxmin:
        fxmin =help
        print('best changed to:',fxmin)
print('final best:',fxmin)

#part b:
fxa = fx(l)
gxa = gx(l)
feas = gxa<=0
fbest = min(fxa[feas])
print('final best:',fbest)

best changed to: 18.332824211918183
best changed to: 17.996466037788352
best changed to: 17.598370193105424
best changed to: 17.141702712256738
best changed to: 16.629629629629626
best changed to: 16.06531697961144
best changed to: 15.451930796589501
best changed to: 14.792637114951164
best changed to: 14.090601969083755
best changed to: 13.348991393374618
best changed to: 12.57097142221109
best changed to: 11.759708089980506
best changed to: 10.918367431070212
best changed to: 10.050115479867545
best changed to: 9.158118270759836
best changed to: 8.245541838134429
best changed to: 7.315552216378659
best changed to: 6.371315439879867
best changed to: 5.415997543025392
best changed to: 4.452764560202575
best changed to: 3.4847825257987464
best changed to: 2.5152174742012483
best changed to: 1.547235439797414
best changed to: 0.5840024569745976
best changed to: -0.3713154398798726
best changed to: -1.315552216378669
best changed to: -2.245541838134433
best changed to: -3.1581182707598456

# Conclusions 
- **At this point, you have some basic knowledge with respect to creating functions, defining variables, writing loops, if statements and scripts.** <br> 
- There are many more matrix operations and manipulations that are enabled with the numpy package. We can't cover all of these in this class, *however*: <br> 
 - Learn as you need to use, tons of online resources. <br>
 - Dr. Johansson's scientific computing notes are a GREAT resource (first three chapters are great introduction). 
 
## Very Important:
**We used 'optimization' as an example above to learn some basic Python operations. HOWEVER: what we did above is enumeration, which is exactly how you should NOT solve an optimization problem after having taken this course!**